#pragma once
#include "CoreMinimal.h"
#include "ERCSaveLoadErrorType.generated.h"

UENUM(BlueprintType)
enum class ERCSaveLoadErrorType : uint8 {
    CheckOK,
    CheckError_Corrupt,
    CheckError_UnspecifiedError,
    CheckError_AlreadyMounted,
    CheckError_UIDError,
    CheckError_NotMount,
    CheckError_FailedFileExtend,
    CheckError_FailedOpenFile,
    CheckError_FailedReadFile,
    SaveOK,
    SaveError_DoesNotExist,
    SaveError_Corrupt,
    SaveError_UnspecifiedError,
    SaveError_AlreadyMounted,
    SaveError_UIDError,
    SaveError_NotFreeSpace,
    SaveError_NotFreeSpaceReWrite,
    SaveError_NotMount,
    SaveError_FailedFileExtend,
    SaveError_FailedCreateFile,
    SaveError_FailedOpenFile,
    SaveError_FailedWriteFile,
    LoadOK,
    LoadError_DoesNotExist,
    LoadError_Corrupt,
    LoadError_UnspecifiedError,
    LoadError_AlreadyMounted,
    LoadError_UIDError,
    LoadError_NotFreeSpace,
    LoadError_NotMount,
    LoadError_FailedFileExtend,
    LoadError_FailedOpenFile,
    LoadError_NotFile,
    LoadError_FailedReadFile,
    DeleteOK,
    DeleteError_DoesNotExist,
    DeleteError_Corrupt,
    DeleteError_UnspecifiedError,
    DeleteError_AlreadyMounted,
    DeleteError_UIDError,
    DeleteError_NotFreeSpace,
    DeleteError_NotMount,
    DeleteError_FailedFileExtend,
    DeleteError_FailedOpenFile,
    DeleteError_FailedDeleteFile,
};

