#pragma once
#include "CoreMinimal.h"
#include "RCRealEventResearchVisionCgabgeSubLevelScriptActorEventTalkDelegate.generated.h"

UDELEGATE(BlueprintCallable) DECLARE_DYNAMIC_MULTICAST_DELEGATE(FRCRealEventResearchVisionCgabgeSubLevelScriptActorEventTalk);

