#pragma once
#include "CoreMinimal.h"
#include "RCRealEventResearchVisionExitSubLevelScriptActorEventTalkDelegate.generated.h"

UDELEGATE(BlueprintCallable) DECLARE_DYNAMIC_MULTICAST_DELEGATE(FRCRealEventResearchVisionExitSubLevelScriptActorEventTalk);

